version: 2

aliases:
  - &restore-cache-deps
      key: dependency-cache-{{ checksum "package.json" }}

  - &save-cache-deps
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - node_modules

defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-deps
      - run: npm install
      - save_cache: *save-cache-deps
      - run: npm run lint
      - run: npm run build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: npm run test
  deploy:
    <<: *defaults
    environment:
      GIT_AUTHOR_NAME: Ionitron
      GIT_AUTHOR_EMAIL: hi@ionicframework.com
      GIT_COMMITTER_NAME: Ionitron
      GIT_COMMITTER_EMAIL: hi@ionicframework.com
    steps:
      - add_ssh_keys:
          fingerprints:
            - "47:33:b0:aa:d8:80:03:30:32:83:4f:3d:5f:58:88:67" # ionitron user key
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: npx semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: stable
